config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'
  resources :docs
end

app/models/doc.rb
class Doc < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
   before_action :find_doc, only:[:show, :edit, :update, :destroy]

	def index
		@docs = Doc.all.order("created_at DESC")
	end

	def show

	end

	def new 
		@doc = current_user.docs.build
	end

	def create
		@doc = current_user.docs.build(doc_params)

		if @doc.save
			redirect_to @doc
		else
			render 'new'
		end
	end

	def edit 
	end

	def update
		if @doc.update(doc_params)
			redirect_to @doc
		else
			render "edit"
		end
	end

	def destroy
		@doc.destroy
		redirect_to docs_path
	end

	private 

	def find_doc 
		@doc = Doc.find(params[:id])
	end

	def doc_params 
		params.require(:doc).permit(:title, :content)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
 =f.input :title
 =f.input :content
 =f.button :submit

app/views/docs/edit.html.haml
%h1 Fix Doc! 

=render 'form'

= link_to "Cancel", doc_path

app/views/docs/index.html.haml
- @docs.each do |doc|
  %h2= link_to doc.title, doc
  %p= time_ago_in_words(doc.created_at)
  %p= truncate(doc.content, length:50 )



= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
%h1 New Doc!  

=render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc)
= link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cabinet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.haml
%h1 Volla! This is the Placeholder! 